export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILUR: 'LOGIN_FAILUR',
    
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILUR: 'LOGOUT_FAILUR'
}


export const userConstants = {
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILUR: 'USER_REGISTER_FAILUR'
}

export const medicineConstants = {
    GET_ALL_MEDICINE_REQUEST: 'GET_ALL_MEDICINE_REQUEST',
    GET_ALL_MEDICINE_SUCCESS: 'GET_ALL_MEDICINE_SUCCESS',
    GET_ALL_MEDICINE_FAILUR: 'GET_ALL_MEDICINE_FAILUR',

    ADD_NEW_MEDICINE_REQUEST: 'ADD_NEW_MEDICINE_REQUEST',
    ADD_NEW_MEDICINE_SUCCESS: 'ADD_NEW_MEDICINE_SUCCESS',
    ADD_NEW_MEDICINE_FAILUR:  'ADD_NEW_MEDICINE_FAILUR',

    UPDATE_MEDICINE_REQUEST: 'UPDATE_MEDICINE_REQUEST',
    UPDATE_MEDICINE_SUCCESS: 'UPDATE_MEDICINE_SUCCESS',
    UPDATE_MEDICINE_FAILUR:  'UPDATE_MEDICINE_FAILUR',

    DELETE_MEDICINE_REQUEST: 'DELETE_MEDICINE_REQUEST',
    DELETE_MEDICINE_SUCCESS: 'DELETE_MEDICINE_SUCCESS',
    DELETE_MEDICINE_FAILUR:  'DELETE_MEDICINE_FAILUR',
}



export const doctorConstants = {
    GET_ALL_DOCTOR_REQUEST: 'GET_ALL_DOCTOR_REQUEST',
    GET_ALL_DOCTOR_SUCCESS: 'GET_ALL_DOCTOR_SUCCESS',
    GET_ALL_DOCTOR_FAILUR:  'GET_ALL_DOCTOR_FAILUR',

    ADD_NEW_DOCTOR_REQUEST: 'ADD_NEW_DOCTOR_REQUEST',
    ADD_NEW_DOCTOR_SUCCESS: 'ADD_NEW_DOCTOR_SUCCESS',
    ADD_NEW_DOCTOR_FAILUR:  'ADD_NEW_DOCTOR_FAILUR',

     UPDATE_DOCTOR_REQUEST:  'UPDATE_DOCTOR_REQUEST',
     UPDATE_DOCTOR_SUCCESS:  'UPDATE_DOCTOR_SUCCESS',
     UPDATE_DOCTOR_FAILUR:   'UPDATE_DOCTOR_FAILUR',

     DELETE_DOCTOR_REQUEST:  'DELETE_DOCTOR_REQUEST',
     DELETE_DOCTOR_SUCCESS:  'DELETE_DOCTOR_SUCCESS',
     DELETE_DOCTOR_FAILUR:   'DELETE_DOCTOR_FAILUR'
}

export const appointmentConstants = {
    GET_ALL_APPOINTMENT_REQUEST: 'GET_ALL_APPOINTMENT_REQUEST',
    GET_ALL_APPOINTMENT_SUCCESS: 'GET_ALL_APPOINTMENT_SUCCESS',
    GET_ALL_APPOINTMENT_FAILUR:  'GET_ALL_APPOINTMENT_FAILUR',

    ADD_NEW_APPOINTMENT_REQUEST: 'ADD_NEW_APPOINTMENT_REQUEST',
    ADD_NEW_APPOINTMENT_SUCCESS: 'ADD_NEW_APPOINTMENT_SUCCESS',
    ADD_NEW_APPOINTMENT_FAILUR:  'ADD_NEW_APPOINTMENT_FAILUR'
}

export const complainConstants = {
    GET_ALL_COMPLAIN_REQUEST: 'GET_ALL_COMPLAIN_REQUEST',
    GET_ALL_COMPLAIN_SUCCESS: 'GET_ALL_COMPLAIN_SUCCESS',
    GET_ALL_COMPLAIN_FAILUR:  'GET_ALL_COMPLAIN_FAILUR',
    
    ADD_NEW_COMPLAIN_REQUEST: 'ADD_NEW_COMPLAIN_REQUEST',
    ADD_NEW_COMPLAIN_SUCCESS: 'ADD_NEW_COMPLAIN_SUCCESS',
    ADD_NEW_COMPLAIN_FAILUR:  'ADD_NEW_COMPLAIN_FAILUR'

}

export const departmentConstants = {
    GET_ALL_DEPARTMENT_REQUEST: 'GET_ALL_DEPARTMENT_REQUEST',
    GET_ALL_DEPARTMENT_SUCCESS: 'GET_ALL_DEPARTMENT_SUCCESS',
    GET_ALL_DEPARTMENT_FAILUR:  'GET_ALL_DEPARTMENT_FAILUR',

    ADD_NEW_DEPARTMENT_REQUEST: 'ADD_NEW_DEPARTMENT_REQUEST',
    ADD_NEW_DEPARTMENT_SUCCESS: 'ADD_NEW_DEPARTMENT_SUCCESS',
    ADD_NEW_DEPARTMENT_FAILUR:  'ADD_NEW_DEPARTMENT_FAILUR'

}

export const employeeConstants = {
    GET_ALL_EMPLOYEE_REQUEST: 'GET_ALL_EMPLOYEE_REQUEST',
    GET_ALL_EMPLOYEE_SUCCESS: 'GET_ALL_EMPLOYEE_SUCCESS',
    GET_ALL_EMPLOYEE_FAILUR:  'GET_ALL_EMPLOYEE_FAILUR',
    
    ADD_NEW_EMPLOYEE_REQUEST: 'ADD_NEW_EMPLOYEE_REQUEST',
    ADD_NEW_EMPLOYEE_SUCCESS: 'ADD_NEW_EMPLOYEE_SUCCESS',
    ADD_NEW_EMPLOYEE_FAILUR:  'ADD_NEW_EMPLOYEE_FAILUR'

}

export const leaveConstants = {
    GET_ALL_LEAVE_REQUEST: 'GET_ALL_LEAVE_REQUEST',
    GET_ALL_LEAVE_SUCCESS: 'GET_ALL_LEAVE_SUCCESS',
    GET_ALL_LEAVE_FAILUR:  'GET_ALL_LEAVE_FAILUR',
    ADD_NEW_LEAVE_REQUEST: 'ADD_NEW_LEAVE_REQUEST',
    ADD_NEW_LEAVE_SUCCESS: 'ADD_NEW_LEAVE_SUCCESS',
    ADD_NEW_LEAVE_FAILUR:  'ADD_NEW_LEAVE_FAILUR'

}

export const initialDataConstants = {
    GET_ALL_INITIAL_DATA_REQUEST: 'GET_ALL_INITIAL_DATA_REQUEST',
    GET_ALL_INITIAL_DATA_SUCCESS: 'GET_ALL_INITIAL_DATA_SUCCESS',
    GET_ALL_INITIAL_DATA_FAILUR: 'GET_ALL_INITIAL_DATA_FAILUR' 
}
